name: SDK Integration Tests

on: [push]

jobs:
  verify:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Check current path
        runs: echo pwd
