name: SDK Integration Tests

on: [push]

jobs:
  verify:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
              path: ios-main-repo
      - name: Check repos
        run: |
            ls -la
            echo "$PWD"
            mkdir ios-spm-repo
            ls -la
            chmod -R 755 ios-spm-repo
            echo "Overwriting code to local spm repo"
            sudo cp -R ios-main-repo/* ios-spm-repo/
            echo "Adding files to git repo"
            cd ios-spm-repo
            git init
            git remote add origin https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/BranchMetrics/ios-branch-sdk-spm.git
            git fetch
            git checkout GHA-experimental
            git add .
            echo "Commitng the repo"
            git commit -m"Test Commit from GHA"
            echo "Pushing to remote"
            git push origin GHA-experimental
            echo "Done"
      - name: Verify CocoaPods Integration
        run: |
            echo "$PWD"
            cd  ios-main-repo/SDKIntegrationTestApps/iOSReleaseTest-Cocoapods/
            pod update
            xcodebuild test -scheme iOSReleaseTest -workspace iOSReleaseTest.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 13,OS=16.0' | xcpretty && exit ${PIPESTATUS[0]}
      - name: Verify Carthage Integration
        env:
            BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
            echo "$PWD"
            CURR_DIR=$(PWD)
            cd  ios-main-repo/SDKIntegrationTestApps/iOSReleaseTest-Carthage/
            echo "git \"file://${CURR_DIR}\" \"$BRANCH_NAME\" " >> cartfile
            carthage update --use-xcframeworks
            xcodebuild test -scheme iOSReleaseTest -project iOSReleaseTest.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 13,OS=16.0' | xcpretty && exit ${PIPESTATUS[0]}
       
