name: SDK Integration Tests

on: [push]

jobs:
  verify:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install cocoapods
        run: |
            echo "$PWD"
            mkdir -p ./SampleApps/CocoaPods
            cp -R ./SampleApps/SDKIntegrationTestApp/iOSReleaseTest ./SampleApps/CocoaPods/
            cp SampleApps/Podfile SampleApps/CocoaPods/iOSReleaseTest/
            cd SampleApps/CocoaPods/iOSReleaseTest/
            pod update
            xcodebuild test -scheme iOSReleaseTest -workspace iOSReleaseTest.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.0' | xcpretty && exit ${PIPESTATUS[0]}
